set_property PACKAGE_PIN R2 [get_ports {SA}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {SA}]
set_property PACKAGE_PIN T1 [get_ports {SB}] 	 	 	 	 	 
	set_property IOSTANDARD LVCMOS33 [get_ports {SB}] 
set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
	set_property IOSTANDARD LVCMOS33 [get_ports clk] 
set_property PACKAGE_PIN U1 [get_ports {reset}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {reset}] 
 	
set_property PACKAGE_PIN U16 [get_ports {top_led_a2}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {top_led_a2}] 
set_property PACKAGE_PIN E19 [get_ports {top_led_a1}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {top_led_a1}] 
set_property PACKAGE_PIN U19 [get_ports {top_led_a0}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {top_led_a0}] 
set_property PACKAGE_PIN V19 [get_ports {top_led_b2}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {top_led_b2}] 
set_property PACKAGE_PIN W18 [get_ports {top_led_b1}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {top_led_b1}] 
set_property PACKAGE_PIN U15 [get_ports {top_led_b0}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {top_led_b0}]

  